# The pre-commit configuration.
#
# Resources
# ---------
# Documentation:
#   - https://pre-commit.com
# Specification:
#   - https://pre-commit.com/#adding-pre-commit-plugins-to-your-project

default_language_version:
  python: python3.12

repos:
  # Ruff.
  # https://docs.astral.sh/ruff/integrations/#pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Mypy.
  # https://github.com/pre-commit/mirrors-mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
